# Generated by Django 5.2.5 on 2025-08-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="social_media.post",
            ),
        ),
    ]
