# Generated by Django 5.2.5 on 2025-08-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0005_alter_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
    ]
