# Generated by Django 5.2.5 on 2025-08-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0006_rename_user_comment_author_rename_user_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="description",
            new_name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
