# Generated by Django 5.2.5 on 2025-08-11 13:46

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bio"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.user_picture
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Status"
            ),
        ),
    ]
